
spring:
  mail:
    host: smtp.gmail.com
    username: nayanaraj9564@gmail.com
    password: lwxi xoiq cfeh jqhg
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth:  true 

